src/main/java/de/samply/edc/osse/model/FormComment.java
/*
 * Copyright (C) 2015 Working Group on Joint Research, University Medical Center Mainz
 * Contact: info@osse-register.de
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option) any
 * later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *
 * Additional permission under GNU GPL version 3 section 7:
 *
 * If you modify this Program, or any covered work, by linking or combining it
 * with Jersey (https://jersey.java.net) (or a modified version of that
 * library), containing parts covered by the terms of the General Public
 * License, version 2.0, the licensors of this Program grant you additional
 * permission to convey the resulting work.
 */

package de.samply.edc.osse.model;

import java.io.Serializable;

import de.samply.edc.catalog.Vocabulary;
import de.samply.edc.utils.Utils;
import de.samply.store.JSONResource;
import de.samply.store.TimestampLiteral;

/**
 * The Class FormComment.
 */
public class FormComment implements Serializable, Comparable<FormComment> {
    
    /** The Constant serialVersionUID. */
    private static final long serialVersionUID = 1L;

    /** The comment. */
    private String comment;
    
    /** The user uri. */
    private String userURI;
    
    /** The user. */
    private User theUser;
    
    /** The timestamp. */
    private long timestamp;

    /**
     * Instantiates a new form comment.
     *
     * @param comment the comment
     * @param userURI the user uri
     * @param timestamp the timestamp
     */
    public FormComment(String comment, String userURI, long timestamp) {
        this.comment = comment;
        this.userURI = userURI;
        this.timestamp = timestamp;
    }

    /**
     * Instantiates a new form comment.
     *
     * @param data the data
     */
    public FormComment(JSONResource data) {
        readJSONResource(data);
    }

    /**
     * Gets the comment.
     *
     * @return the comment
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the comment.
     *
     * @param comment the new comment
     */
    public void setComment(String comment) {
        this.comment = comment;
    }

    /**
     * Gets the user real name.
     *
     * @return the user real name
     */
    public String getUserRealName() {
        if(theUser == null) {
            theUser = new User(Utils.getDatabase(), userURI);
            theUser.load(false, false);
        }
        
        return theUser.getUserRealName();
    }
    
    /**
     * Gets the timestamp.
     *
     * @return the timestamp
     */
    public long getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the timestamp.
     *
     * @param timestamp the new timestamp
     */
    public void setTimestamp(long timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * Read json resource.
     *
     * @param data the data
     */
    public void readJSONResource(JSONResource data) {
        if (data == null)
            return;

        this.comment = data.getProperty(Vocabulary.Comment.commentText).getValue();
        this.timestamp = data.getProperty(Vocabulary.Comment.commentTimestamp).asLong();
        this.userURI = data.getProperty(Vocabulary.Comment.commentUserURI).getValue();
    }

    /**
     * To json resource.
     *
     * @return the JSON resource
     */
    public JSONResource toJSONResource() {
        JSONResource commentResource = new JSONResource();
        commentResource.addProperty(Vocabulary.Comment.commentTimestamp, new TimestampLiteral(timestamp));
        commentResource.addProperty(Vocabulary.Comment.commentUserURI, userURI);
        commentResource.addProperty(Vocabulary.Comment.commentText, comment);

        return commentResource;
    }

    /* (non-Javadoc)
     * @see java.lang.Comparable#compareTo(java.lang.Object)
     */
    @Override
    public int compareTo(FormComment other) {
        if (other.getTimestamp() > getTimestamp())
            return -1;

        if (other.getTimestamp() < getTimestamp())
            return 1;

        return 0;
    }
}

src/main/webapp/components/commonFormButtons.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core" >
<body>
    <ui:composition>
        <h:commandLink styleClass="btn btn-success" style="margin-right: 20px;" id="save" action="#{formviewer.save}" rendered="#{formviewer.formState == 'open'}">
        <i class="fa fa-check fa-fw" /> #{msg.formbutton_save} 
        </h:commandLink>
        <h:commandLink styleClass="btn btn-danger" value="" id="cancel" immediate="true"
                    actionListener="#{sessionBean.cancelPage()}" rendered="#{formviewer.formState == 'open'}">
                    <i class="fa fa-undo fa-fw" /> #{msg.cancel}
            <f:param name="disableValidation" value="true" />
        </h:commandLink>
    </ui:composition>
</body>
</html>

src/main/webapp/components/dialogFormStatus.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      >
<body>
<ui:composition>


<p:dialog header="Change Status" widgetVar="changeFormStatusDialog" appendTo="@(body)" closeOnEscape="true" modal="true">
<h:form>
<h:panelGroup layout="block" id="topFormPanel" styleClass="panel panel-default">
<h:panelGroup layout="block" styleClass="panel-body">

<h:panelGroup layout="block" styleClass="row">
<h:panelGroup layout="block" styleClass="col-md-12">
Currently the form is in the state: #{formviewer.form.formState} <br />
Select the state you want to change to, or press cancel.
</h:panelGroup>
</h:panelGroup>
<br />
<h:panelGroup layout="block" styleClass="row">
<h:panelGroup layout="block" styleClass="col-md-4">
<h:outputLabel for="username">New state:</h:outputLabel>
</h:panelGroup>
<h:panelGroup layout="block" styleClass="col-md-8">
    <h:selectOneMenu value="#{formviewer.newStatus}" id="newStatus" name="newStatus">
          <f:selectItems value="#{formviewer.possibleNewStatus}"/>
    </h:selectOneMenu>    
</h:panelGroup>
</h:panelGroup>
<br />
<h:panelGroup layout="block" styleClass="row">
Optional comment:
</h:panelGroup>
<h:panelGroup layout="block" styleClass="row">
<h:inputTextarea rows="5" cols="80" value="#{formviewer.entries['statusChangeComment']}"></h:inputTextarea>
</h:panelGroup>
<p:commandButton style="margin-right: 10px" styleClass="btn btn-success" ajax="false" type="submit" value="Change Status" action="#{formviewer.changeToNewStatus()}" />
<p:commandButton styleClass="btn btn-danger" value="#{msg.cancel}" onclick="PF('changeFormStatusDialog').close()"/>

</h:panelGroup>
</h:panelGroup>
</h:form>
</p:dialog>

</ui:composition>
</body>
</html>

src/main/webapp/components/episodeCarouselOSSE.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      >
<body>
<ui:composition>
<ui:fragment rendered="#{sessionBean.showEpisodeCarousel()}">

<h:form prependId="false">

<hr />
<h:panelGroup style="font-size: 30px">
    Episodes <h:panelGroup styleClass="counter">(#{sessionBean.currentCase.episodes.size()})</h:panelGroup>
</h:panelGroup>
<h:panelGroup styleClass="actions" style="vertical-align: super;">

                        <ui:repeat var="item" value="#{formviewer.contextMenuList}">
                                <ui:fragment rendered="#{item.sure == 'true'}">
                                    <h:commandLink onclick="return confirm('#{item.confirmText}')" actionListener="#{formviewer.goTo(item.link)}" styleClass="button filter" style="margin: 8px;">
                                            <i class="fa #{item.icon}"></i> #{item.text}</h:commandLink>
                                            
                                </ui:fragment>

                                <ui:fragment rendered="#{!item.sure }">
                                    <h:commandLink actionListener="#{formviewer.goTo(item.link)}" styleClass="button filter" style="margin: 8px;">
                                            <i class="fa #{item.icon}"></i> #{item.text}</h:commandLink>
                                </ui:fragment>
                            </ui:repeat>
                            
<!-- 	<h:link href="" styleClass="button filter">Filter</h:link> -->


</h:panelGroup>

<ui:fragment rendered="#{sessionBean.currentCase.episodes.size() > 0}">

<h:panelGroup layout="block" styleClass="clearfix"></h:panelGroup>

<h:panelGroup style="background-color: #ccc;" layout="block" id="episode-slider">
<ui:repeat id="theVisits" var="item" value="#{sessionBean.currentCase.episodes}">
    <h:commandLink rendered="#{!sessionBean.hasCurrentEpisode()}" action="#{sessionBean.switchEpisode(item)}" title="#{item.name}" styleClass="tab #{item.allFormsStatusText()}" style="transform: scale(1.0);">#{item.name}<br />#{item.optionalText}</h:commandLink>
    <h:commandLink rendered="#{sessionBean.hasCurrentEpisode()}" action="#{sessionBean.switchEpisode(item)}" title="#{item.name}" styleClass="tab #{item.allFormsStatusText()}" >#{item.name}<br />#{item.optionalText}</h:commandLink>
</ui:repeat>
</h:panelGroup>


<c:if test="#{sessionBean.showEpisodeCarousel()}">
<h:outputScript target="body">
        $(document).ready(function(){
            $('#episode-slider').slick({
        slidesToScroll: 1,
        centerMode: true,
        centerPadding: '60px',
        infinite: false,
        dots: false,
        slide: 'a',
        variableWidth: true,
                  initialSlide: #{sessionBean.currentPositionCurrentEpisodeInCurrentCase},
                });
        });
</h:outputScript>
</c:if>
</ui:fragment>

</h:form>

</ui:fragment>

</ui:composition>
</body>
</html>

src/main/webapp/components/formHeadPanelSymbol.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html" 
      xmlns:f="http://java.sun.com/jsf/core" 
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:p="http://primefaces.org/ui"
      >
<body>
<ui:composition>
<h:panelGroup title="#{msg.formstate_signed}" id="formstate_signed_symbol" style="padding-left: 10px" styleClass="fa fa-lock hasTooltip" rendered="#{formviewer.formState=='validated'}" />

<h:panelGroup title="#{msg.formstate_reported}" id="formstate_reported_symbol" style="padding-left: 10px" styleClass="fa fa-envelope hasTooltip" rendered="#{formviewer.formState=='reported'}" />

</ui:composition>
</body>
</html>

src/main/webapp/components/formcomments.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core" xmlns:c="http://java.sun.com/jsp/jstl/core" xmlns:p="http://primefaces.org/ui">
<body>
    <ui:composition>
    
    <p:overlayPanel id="commentPanel" for="commentBtn" hideEffect="fade" dynamic="true" style="width:600px">
        <p:dataTable var="comment" value="#{formviewer.formComments}" rows="5" paginator="true">
            <p:column headerText="#{ossemsg.formcomments_timestamp}" width="20%">
                <h:outputText value="#{comment.timestamp}">
                    <f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss" type="date" />
                </h:outputText>
            </p:column>
            <p:column headerText="#{ossemsg.formcomments_who}" width="20%">
                <h:outputText value="#{comment.userRealName}" />
            </p:column>
            <p:column headerText="#{ossemsg.formcomments_comment}" width="60%">
                <h:outputText value="#{comment.comment}" />
            </p:column>
        </p:dataTable>
    
    </p:overlayPanel>
    
    </ui:composition>
</body>
</html>

src/main/webapp/components/navbar.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:c="http://java.sun.com/jsp/jstl/core">
    <h:form prependId="false">
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

            <div class="navbar-header">

                <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span> <span
                        class="icon-bar"></span> <span class="icon-bar"></span> <span
                        class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.xhtml?form="> OSSE<span
                    class="titleOrange">.forms</span>
                </a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li
                        class="#{view.viewId == '/index.xhtml' and sessionBean.currentFormName == 'patientlist' ? 'active' : ''}"><a
                        href="index.xhtml?form=">Startpage</a></li>

                    <li class="dropdown"><a href="#" class="dropdown-toggle"
                        data-toggle="dropdown">Administration<span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li
                                class="#{view.viewId == '/index.xhtml?form=locationlist' ? 'active' : ''}"><a
                                href="index.xhtml?form=locationlist">#{msg.link_grouplist}</a></li>
                            <li
                                class="#{view.viewId == '/index.xhtml?form=userlist' ? 'active' : ''}"><a
                                href="index.xhtml?form=userlist">#{msg.link_userlist}</a></li>
                            <!-- 							<li	class="#{view.viewId == '/index.xhtml?form=deleteduserlist' ? 'active' : ''}"><a -->
                            <!-- 								href="index.xhtml?form=deleteduserlist">#{msg.link_undeleteuserlist}</a></li> -->
                            <li
                                class="#{view.viewId == '/index.xhtml?form=rolelist' ? 'active' : ''}"><a
                                href="index.xhtml?form=rolelist">Roles</a></li>
                            <li
                                class="#{view.viewId == '/index.xhtml?form=register_forms_sorter' ? 'active' : ''}"><a
                                href="index.xhtml?form=register_forms_sorter">Register Forms
                                    Config</a></li>

                        </ul></li>

                </ul>
                <ul class="nav navbar-nav navbar-right navbar-user">
                    <li id="userButton" class="dropdown user-dropdown"><a href="#"
                        class="dropdown-toggle userLoginDropdown" data-toggle="dropdown">
                            #{sessionBean.currentUser.username} <b class="caret"></b>
                    </a>
                        <ul id="userPanel" class="dropdown-menu">
                            <li><a href="index.xhtml?form=pwchange"><i
                                    class="fa fa-user"></i> #{msg.link_pwchange}</a></li>
                            <li><a href="index.xhtml?form=user_contact"><i
                                    class="fa fa-list"></i> #{bmb_msg.contact_details}</a></li>
                            <li class="divider"></li>
                            <li><h:commandLink action="#{sessionBean.logout()}"
                                    value="#{msg.logout}" styleClass="fa fa-sign-out" /></li>
                        </ul></li>
                </ul>
                <!-- Dialoges must be put here or for some reason they are below their own layer? -->
                <ui:include src="/components/contextmenu_dialogues.xhtml" />


            </div>

            <c:choose>
                <c:when test="#{applicationBean.samplyProject == 'transarnet'}">
                    <ui:include src="/components/navigationBreadcrumbsTransarnet.xhtml" />
                </c:when>
                <c:otherwise>
                    <ui:include src="/components/navigationBreadcrumbs.xhtml" />
                </c:otherwise>
            </c:choose>

        </nav>
    </h:form>

</ui:composition>

src/main/webapp/components/navbar_left.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html">
<body>
    <ui:composition>

        <h:form>

            <h:panelGroup layout="block" styleClass="float-left">
                <h:panelGroup layout="block" styleClass="col" id="logo">
                        <h:graphicImage width="60" height="23" alt="OSSE" library="images" name="osse/osse_logo_white.svg" />
                        <h:panelGroup styleClass="osseLogoSideText" rendered="#{applicationBean.isBridgehead()}">Bridgehead</h:panelGroup>
                </h:panelGroup>
<ui:fragment rendered="#{sessionBean.currentRole.isAdminRole() or sessionBean.currentRole.isLocalAdminRole()}">
                <h:commandLink styleClass="col"
                    action="#{sessionBean.goStartPage()}" id="list_adminstuff">Administration
                </h:commandLink>
</ui:fragment>		
<ui:fragment rendered="#{!(sessionBean.currentRole.isAdminRole() or sessionBean.currentRole.isLocalAdminRole() or sessionBean.currentRole.isPatientRole())}">		
                <h:commandLink styleClass="col"
                    action="#{sessionBean.goStartPage()}" id="list_patients">List of patients
                </h:commandLink>
</ui:fragment>				
            </h:panelGroup>
        </h:form>

    </ui:composition>
</body>
</html>

src/main/webapp/components/navbar_right.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:c="http://java.sun.com/jsp/jstl/core"
    xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
    >
<body>
    <ui:composition>
        <h:form prependId="false">
        <h:panelGroup layout="block" styleClass="float-right">
            <h:panelGroup layout="block" styleClass="col" id="search">
                <!-- 					<h:inputText placeholder="search" /> -->
<ui:fragment rendered="#{sessionBean.hasMultipleRoles()}">
<h:panelGroup style="color: #fff; font-weight: bold;">Role: </h:panelGroup>				
<h:selectOneMenu valueChangeListener="#{sessionBean.changeRoleAction}" onchange="submit()"
        styleClass="#{!component.valid ? 'error':''}" requiredMessage="#{msg.required}" required="true" value="#{sessionBean.selectedRole}" id="role" name="role">
        <f:selectItems value="#{sessionBean.roleList}"/>
</h:selectOneMenu>

</ui:fragment>
                
            </h:panelGroup>

            <!-- 	<h:link styleClass="col" href="#" id="help">?</h:link> -->

            <h:panelGroup layout="block" styleClass="dropdown">
            <h:outputLink value="#" styleClass="col dropdown-toggle"
                id="user" pt:data-toggle="dropdown" pt:aria-expanded="false"> 
                <h:panelGroup styleClass="fa fa-user" style="font-size: 30px;" aria-hidden="true"></h:panelGroup>
<c:choose>
    <c:when test="#{sessionBean.currentRole.isPatientRole()}">
                <h:panelGroup style="margin-left: 4px; float:right;">
                                            <h:panelGroup
                                                id="idatFirstNameProfileLink"
                                                pt:data-tempid="#{sessionBean.currentPatient.pseudonym}"
                                                pt:data-subject="vorname" />&#160;<h:panelGroup
                                                id="idatLastNameProfileLink"
                                                pt:data-tempid="#{sessionBean.currentPatient.pseudonym}"
                                                pt:data-subject="nachname" /> 
                    <b class="caret"></b> 
                </h:panelGroup>
    </c:when>
    <c:otherwise>
                <h:panelGroup style="margin-left: 4px; float:right;">
                    #{sessionBean.currentUser.userRealName}
                    <b class="caret"></b> 
                </h:panelGroup>
    </c:otherwise>
</c:choose>
                
                <!-- 					<h:panelGroup id="notification_count">2</h:panelGroup> -->
            </h:outputLink>

            
            <ul role="menu" class="dropdown-menu">
                <li><a href="profile.xhtml" style="font-weight: normal; text-decoration:none;">Edit Profile</a></li>
                <li class="divider"></li>
                <li><h:commandLink action="#{sessionBean.logout()}" style="font-weight: normal; text-decoration:none;"><i class="fa fa-sign-out"></i> Logout</h:commandLink>
 <!-- Invisible Button for JS to log out, LEAVE IT HERE! --> 
 <!-- 									<h:commandButton value="#{msg.logout} (#{sessionBean.currentUser.username})" id="logoutButtonVar" action="#{sessionBean.logout}" icon="ui-icon-extlink" ajax="false" style="display:none" /> -->
                </li>
            </ul>
            
            </h:panelGroup>
        </h:panelGroup>
        </h:form>
    </ui:composition>
</body>
</html>

src/main/webapp/components/rightflag.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"   
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      >
<body>
<ui:composition>

<!-- this is silly to force the forms to have this param set to show this menu
    the decision is this menu is shown must depend only on some mojo that a context menu entries are actually present
    which should be provided by the view-bean
    so well...
    TODO: do this
 -->
<ui:fragment rendered="#{!formviewer.formParam['hideRightFlag']}">

<!-- Evtl unterschiedliche buttongrößen beim hovern? -->
<ul class="rightFlag">
    <ui:fragment rendered="#{!sessionBean.isEditmode}">
        <li>
            <button class="btn btn-default btn-sm" data-toggle="dropdown" style="float: right;" >
                <span class="fa fa-cogs rightFlagIcon pull-left"></span>
                <span class="slideText">Context</span>
                
            </button>
            <ul class="dropdown-menu pull-right" role="menu">


<!-- VISIT -->
        <ui:fragment rendered="#{sessionBean.hasCurrentPatient()}">
        <li>Visit</li>
        <li><p:commandLink actionListener="#{sessionBean.goNewVisitByButton()}" ><i class="fa fa-plus"></i> #{msg.link_newvisit}</p:commandLink></li>
        <ui:fragment rendered="#{sessionBean.hasCurrentVisit() and sessionBean.currentUser.isGlobalAdmin()}">
            <li><p:commandLink actionListener="#{sessionBean.goEditVisit()}" ><i class="fa fa-edit"></i> #{msg.edit_visit_link}</p:commandLink></li>
            <li><p:commandLink onclick="confirmationDeleteVisit.show()" ><i class="fa fa-eraser"></i> #{msg.delete_visit_link}</p:commandLink></li>
            <ui:fragment rendered="#{formviewer.visitIsReported}">
                <li><p:commandLink onclick="confirmationSignAllHead.show()" ><i class="fa fa-lock"></i> #{msg.link_signvisit}</p:commandLink></li>
            </ui:fragment>
        </ui:fragment>
        <ui:fragment rendered="#{sessionBean.hasCurrentVisit() and !(formviewer.visitIsReported or formviewer.visitIsValidated)}">
            <li><p:commandLink onclick="confirmationReportAllHead.show()"  ><i class="fa fa-flag"></i> #{msg.link_reportvisit}</p:commandLink></li>
        </ui:fragment>
        <li class="divider"></li>
        </ui:fragment>


<!-- FORM -->
        <li>Form</li>
        <ui:fragment rendered="#{!sessionBean.isCurrentFormUnique() and formviewer.formState=='open'}">
        <li><p:commandLink onclick="confirmationImport.show()" ><i class="fa fa-upload"></i> #{msg.formbutton_import}</p:commandLink></li>
        </ui:fragment>
        <ui:fragment rendered="#{formviewer.formState=='open'}">
        <li><p:commandLink onclick="confirmationReport.show()" ><i class="fa fa-flag"></i> #{msg.formbutton_report}</p:commandLink></li>
        </ui:fragment>
        <ui:fragment rendered="#{formviewer.formState=='reported'}">
        <ui:fragment rendered="#{!sessionBean.currentUser.globalAdmin}">
        <li><p:commandLink onclick="confirmationReportTakeback.show()" ><i class="fa fa-flag-o"></i> #{msg.formbutton_report_takeback}</p:commandLink></li>
        </ui:fragment>
        <ui:fragment rendered="#{sessionBean.currentUser.globalAdmin}">
        <li><p:commandLink onclick="confirmationSign.show()" ><i class="fa fa-lock"></i> #{msg.formbutton_signieren}</p:commandLink></li>
        <li><p:commandLink onclick="confirmationRefuse.show()" ><i class="fa fa-flash"></i> #{msg.formbutton_refuse}</p:commandLink></li>
        </ui:fragment>
        </ui:fragment>
        <ui:fragment rendered="#{formviewer.formState=='validated'}">
        <li><p:commandLink onclick="confirmationBreakSign.show()" ><i class="fa fa-unlock"></i> #{msg.formbutton_sign_takeback}</p:commandLink></li>
        </ui:fragment>
    </ul>
        </li>
    </ui:fragment>
</ul>

</ui:fragment>

</ui:composition>
</body>
</html>